env:
  es2020: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - never
